# Generated by Django 6.1 on 2026-08-06 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inquiry_type', models.CharField(choices=[('organization', 'Healthcare Organization / Clinic / Provider'), ('family', 'Family / Caregiver / Individual Client'), ('therapist', 'Qualified Therapist (Joining Talent Pool)'), ('other', 'Other General Inquiry')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_or_profession', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('therapist_type_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('vacancy_context', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
