# Generated by Django 5.2.15 on 2026-08-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thera_App', '0003_partnerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='3-Year Partner Plan', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='Thera_App.partnerprofile')),
            ],
            options={
                'verbose_name': 'Recruitment Partner Subscription',
                'verbose_name_plural': 'Recruitment Partner Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Thera_App.partnerprofile')),
            ],
            options={
                'verbose_name': 'Razorpay Payment Log',
                'verbose_name_plural': 'Razorpay Payment Logs',
            },
        ),
    ]
