# Generated by Django 5.2.15 on 2026-08-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thera_App', '0004_partnersubscription_razorpaypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('job_role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('placed', 'Placed'), ('unavailable', 'Unavailable')], default='available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
            },
        ),
        migrations.CreateModel(
            name='CandidateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('request_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Thera_App.candidate')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requests', to='Thera_App.partnerprofile')),
            ],
            options={
                'verbose_name': 'Partner Candidate Request',
                'verbose_name_plural': 'Partner Candidate Requests',
                'unique_together': {('partner', 'candidate')},
            },
        ),
    ]
